export const langs = new Map([
  ["af-ZA", "Afrikaans"],
  ["am-ET", "አማርኛ"],
  ["az-AZ", "Azərbaycanca"],
  ["id-ID", "Bahasa Indonesia"],
  ["ms-MY", "Bahasa Melayu"],
  ["ca-ES", "Català"],
  ["cs-CZ", "Čeština"],
  ["da-DK", "Dansk"],
  ["de-DE", "Deutsch"],
  ["eu-ES", "Euskara"],
  ["fil-PH", "Filipino"],
  ["fr-FR", "Français"],
  ["jv-ID", "Basa Jawa"],
  ["gl-ES", "Galego"],
  ["gu-IN", "ગુજરાતી"],
  ["hr-HR", "Hrvatski"],
  ["zu-ZA", "IsiZulu"],
  ["is-IS", "Íslenska"],
  ["kn-IN", "ಕನ್ನಡ"],
  ["km-KH", "ភាសាខ្មែរ"],
  ["lv-LV", "Latviešu"],
  ["lt-LT", "Lietuvių"],
  ["ml-IN", "മലയാളം"],
  ["mr-IN", "मराठी"],
  ["hu-HU", "Magyar"],
  ["lo-LA", "ລາວ"],
  ["nl-NL", "Nederlands"],
  ["ne-NP", "नेपाली भाषा"],
  ["nb-NO", "Norsk bokmål"],
  ["pl-PL", "Polski"],
  ["ro-RO", "Română"],
  ["si-LK", "සිංහල"],
  ["sl-SI", "Slovenščina"],
  ["su-ID", "Basa Sunda"],
  ["sk-SK", "Slovenčina"],
  ["fi-FI", "Suomi"],
  ["sv-SE", "Svenska"],
  ["ka-GE", "ქართული"],
  ["hy-AM", "Հայերեն"],
  ["te-IN", "తెలుగు"],
  ["vi-VN", "Tiếng Việt"],
  ["tr-TR", "Türkçe"],
  ["el-GR", "Ελληνικά"],
  ["bg-BG", "български"],
  ["ru-RU", "Pусский"],
  ["sr-RS", "Српски"],
  ["uk-UA", "Українська"],
  ["ko-KR", "한국어"],
  ["ja-JP", "日本語"],
  ["hi-IN", "हिन्दी"],
  ["th-TH", "ภาษาไทย"],
  ["bn-BD", "বাংলা - বাংলাদেশ"],
  ["bn-IN", "বাংলা - ভারত"],
  ["en-AU", "English - Australia"],
  ["en-CA", "English - Canada"],
  ["en-IN", "English - India"],
  ["en-KE", "English - Kenya"],
  ["en-TZ", "English - Tanzania"],
  ["en-GH", "English - Ghana"],
  ["en-NZ", "English - New Zealand"],
  ["en-NG", "English - Nigeria"],
  ["en-ZA", "English - South Africa"],
  ["en-PH", "English - Philippines"],
  ["en-GB", "English - United Kingdom"],
  ["en-US", "English - United States"],
  ["es-AR", "Español - Argentina"],
  ["es-BO", "Español - Bolivia"],
  ["es-CL", "Español - Chile"],
  ["es-CO", "Español - Colombia"],
  ["es-CR", "Español - Costa Rica"],
  ["es-EC", "Español - Ecuador"],
  ["es-SV", "Español - El Salvador"],
  ["es-ES", "Español - España"],
  ["es-US", "Español - Estados Unidos"],
  ["es-GT", "Español - Guatemala"],
  ["es-HN", "Español - Honduras"],
  ["es-MX", "Español - México"],
  ["es-NI", "Español - Nicaragua"],
  ["es-PA", "Español - Panamá"],
  ["es-PY", "Español - Paraguay"],
  ["es-PE", "Español - Perú"],
  ["es-PR", "Español - Puerto Rico"],
  ["es-DO", "Español - República Dominicana"],
  ["es-UY", "Español - Uruguay"],
  ["es-VE", "Español - Venezuela"],
  ["it-IT", "Italiano - Italia"],
  ["it-CH", "Italiano - Svizzera"],
  ["pt-BR", "Português - Brasil"],
  ["pt-PT", "Português - Portugal"],
  ["sw-TZ", "Kiswahili - Tanzania"],
  ["sw-KE", "Kiswahili - Kenya"],
  ["ta-IN", "தமிழ் - இந்தியா"],
  ["ta-SG", "தமிழ் - சிங்கப்பூர்"],
  ["ta-LK", "தமிழ் - இலங்கை"],
  ["ta-MY", "தமிழ் - மலேசியா"],
  ["ur-PK", "پاکستان - اُردُو"],
  ["ur-IN", "بھارت - اُردُو"],
  ["cmn-Hans-CN", "中文 - 普通话 (中国大陆)"],
  ["cmn-Hans-HK", "中文 - 普通话 (香港)"],
  ["cmn-Hant-TW", "中文 - 中文 (台灣)"],
  // safari only can use yue-Hans or yue-Hant, But Chrome use these will all print traditional Chinese
  ["yue-Hant-HK", "中文 - 粵語 (香港)"],
]);
